### ISSUE TITLE
setting a rule

### ISSUE THREAD

**Issue by jtolksdo** [Art-of-WiFi/UniFi-API-client#181]
Hi,
apologies, I'm lost.
Is there a function which allows me to set an existing traffic rule to "allow" or "block"?
Thanks a million!

**Comment by jtolksdo** [comment]
@malle-pietje thanks for the swift reply. On my Dream Machine I can go in settings to "Traffic Management". There, I can define "Traffic Rules" and set them to "allow" or "block.
![image](https://user-images.githubusercontent.com/4997922/205888116-056010e4-3076-4e93-a7ee-4360edc107b2.png)

**Comment by malle-pietje** [comment]
OK, so they changed the terminology used for "Traffic Restrictions" with version 7.2... Need to find the time to check whether this also involves new API routes.

**Comment by jtolksdo** [comment]
you rock! Thank you!

**Comment by Brovning** [comment]
Hello,
any updates on this topic?

**Comment by malle-pietje** [comment]
Had a first look and the basic logic looks quite straightforward. Need to figure out how to document this because of the applications and application groups. The names mappings for these still aren’t available through the API and without that information it’s going to be pretty tricky to use…

Any suggestions?

**Comment by Brovning** [comment]
The user has to click on edit, so that he can copy the unique ruleID from the URL:
![image](https://user-images.githubusercontent.com/39644775/215022834-09c1d00a-8dc0-449e-82ee-66bbef66bd1a.png)

Afterwards your implemented function for "pausing" the referred traffic rule with ruleID can be used.

I think, that this would be the easiest approach...
