### ISSUE TITLE
API authentication via ubiquity account - implicit 2FA introduced

### ISSUE THREAD

**Issue by cheseremtitus24** [Art-of-WiFi/UniFi-API-client#255]
Therefore, API to authorize guest access is broken (have been unable to create/use a local user account), I am suggesting that if it is possible to update the api so that it takes in a recovery code as an input parameter, thereby allowing for continued api operation to authorize guest access it's a long-shot, not ideal. (All sites are unable to authorize-guest access - assist in resolving this issue)

**Comment by malle-pietje** [comment]
Not going to implement this because this assumes human interaction; simply use a local admin account which doesn't require MFA instead.

On our blog we have published a post which explains how to create a local admin account on UniFi OS consoles and on software-based controllers:
https://artofwifi.net/blog/important-update-for-all-unifi-api-users-switch-to-local-admin-accounts-before-july-2024
