### ISSUE TITLE
Authenticate Guest clients for external portal UniFi

### ISSUE THREAD

**Issue by TheFedelino01** [Art-of-WiFi/UniFi-API-client#57]
Can somebody share a simple PHP code of a website used in /guest/s/default to auth clients when they request to access a free open network managed with an external portal in Ubiquiti? 
I looked through this repository but I found a guest auth.php but the mac address has to be inserted manually and so I wasn't able to use it for my purpose (Auth guests with a website when they access a network - External Captive Portal).
Thank you, waiting for an answer

**Comment by malle-pietje** [comment]
There is no way around using the MAC address because that is what the UniFi controller uses to identify the device. On your website you'll need to find a way to extract the client MAC from the URL (it's passed as a GET parameter) and use when requesting the authorization.

Other than that it's pretty straightforward PHP programming.

PS: not every website can be used as a captive portal, especially with Wordpress you will run into a number of challenges...

**Comment by TheFedelino01** [comment]
Thank you! I didn't know that UniFi Controller sent also some parameters..
The MAC address of the device can be found with: $_GET["id"] and the MAC address of the AP simply by $_GET["id"].

**Comment by TheFedelino01** [comment]
... the AP simply by $_GET["ap"].
