### ISSUE TITLE
All wlan reseting

### ISSUE THREAD

**Issue by mariosutalo** [Art-of-WiFi/UniFi-API-client#6]
Hello, i have sucessfully added scheduled task that enables and disables certain wlan network, using disable_wlan function, only issue is that when this funtion is called, controller disables all wlans for brief period and then enables them again, thus disconnecting client that are conected to those networks. Controller version is: 5.4.14.

**Comment by malle-pietje** [comment]
This is caused by how the device provisioning process works with the UniFi platform. With each controller version I am seeing improvements so that the device’s primary function is not being temporarily disabled with each comfig change. Maybe you can test this out with a more recent 5.5.X or 5.6.X release.

**Comment by mariosutalo** [comment]
ok, will try. Thank you.
