### ISSUE TITLE
Controller V6 Support

### ISSUE THREAD

**Issue by MikeSiekkinen** [Art-of-WiFi/UniFi-API-client#75]
Out of the box this doesn't seem to work with verison 6 of the controller.  Is this currently under development?  If not I could help work on that.

**Comment by malle-pietje** [comment]
We see no issues using the client with controller version 6.0.27. I must say this is a test environment due to the fact we don’t yet trust this version enough for production use.

Please share the exact issues you are experiencing, which exact version and on which controller platform (software install, CloudKey, UDM, or UDP PRO).
